# This is a basic workflow to help you get started with Actions

name: Build OGG FMT Header

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: tools/ogg-fmt-header

    - uses: actions/upload-artifact@v2
      with:
        name: ogg-fmt-header
        path: tools/ogg-fmt-header/dist/windows
